[project]
name = "curses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyperclip>=1.9.0",
]

[project.scripts]
vimtodo = "main:main"
